services:
  picator.api:
    image: ${DOCKER_REGISTRY-}picatorapi
    build:
      context: .
      dockerfile: Picator.Api/Dockerfile
    depends_on:
      - sqlserver
    networks:
      - mssql_network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - mssql_network

networks:
    mssql_network:
        driver: bridge

