---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: picator-realtime
  labels:
    app: picator-realtime
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: picator-realtime
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: picator-realtime
    spec:
      containers:
      - name: picator-realtime
        image: picator-realtime:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: picator-realtime-env
        - secretRef:
            name: picator-realtime-secrets
      terminationGracePeriodSeconds: 180