resources:
- deployment.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: picator-realtime-env
  literals:
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY=in_memory
    - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
    - HTTP_PORTS=8080
    - PICATORDB_HOST=sql
    - PICATORDB_PORT=1433
    - PICATORDB_USERNAME=sa
    - PICATORDB_PASSWORD=54Delta45!
    - PICATORDB_URI=mssql://sql:1433/PicatorDB
    - PICATORDB_JDBCCONNECTIONSTRING=jdbc:sqlserver://sql:1433;trustServerCertificate=true;databaseName=PicatorDB
    - PICATORDB_DATABASE=PicatorDB
    - ASPNETCORE_URLS=http://+:8080;

secretGenerator:
- name: picator-realtime-secrets
  envs:
  - .picator-realtime.secrets
