<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>a2fd4fbf-40ed-457c-91d5-1223a38b2817</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Microsoft.EntityFrameworkCore.SqlServer" Version="13.0.1" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
    <PackageReference Include="MagicOnion.Server" Version="7.0.6" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Picator.Realtime.Common\Picator.Realtime.Common.csproj" />
    <ProjectReference Include="..\Picator.ServiceDefaults\Picator.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Picator.Service\Picator.Service.csproj" />
  </ItemGroup>
</Project>