<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FastEndpoints" Version="1.0.1" />
    <PackageReference Include="FastEndpoints.Swagger" Version="1.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Facebook" Version="7.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="7.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="7.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.0.0" />
    <PackageReference Include="NSwag.AspNetCore" Version="13.19.0" />
    <PackageReference Include="Scrutor" Version="4.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Picator.Service\Picator.Service.csproj" />
  </ItemGroup>

</Project>
