<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<ProduceReferenceAssembly>true</ProduceReferenceAssembly>
		<LangVersion>10</LangVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DebugType>portable</DebugType>
		<DebugSymbols>true</DebugSymbols>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="music.mp3" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="music.mp3" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.0" />
		<PackageReference Include="Grpc.Net.Client" Version="2.52.0" />
		<PackageReference Include="MagicOnion.Client" Version="5.1.6" />
		<PackageReference Include="MarcTron.Admob" Version="1.9.0.3" />
		<PackageReference Include="Microsoft.AppCenter.Analytics" Version="5.0.1" />
		<PackageReference Include="Microsoft.AppCenter.Crashes" Version="5.0.1" />
		<PackageReference Include="Plugin.MediaManager.Forms" Version="1.1.1" />
		<PackageReference Include="Rg.Plugins.Popup" Version="2.1.0" />
		<PackageReference Include="SkiaSharp.Views.Forms" Version="2.88.3" />
		<PackageReference Include="Xamarin.CommunityToolkit" Version="2.0.6" />
		<PackageReference Include="Xamarin.FFImageLoading.Forms" Version="2.4.11.982" />
		<PackageReference Include="Xamarin.FFImageLoading.Svg.Forms" Version="2.4.11.982" />
		<PackageReference Include="Xamarin.FFImageLoading.Transformations" Version="2.4.11.982" />
		<PackageReference Include="Xamarin.Forms" Version="5.0.0.2578" />
		<PackageReference Include="Xamarin.Essentials" Version="1.7.5" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Update="Controls\CopyButton.xaml">
	    <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Controls\ShareButton.xaml">
	    <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Views\StartNewGamePage.xaml">
	    <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Views\TimerGameView.xaml">
	    <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
	  </EmbeddedResource>
	</ItemGroup>
</Project>