<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<ProduceReferenceAssembly>true</ProduceReferenceAssembly>
		<LangVersion>10</LangVersion>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DebugType>portable</DebugType>
		<DebugSymbols>true</DebugSymbols>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="music.mp3" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="music.mp3" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Storage.Blobs" Version="12.16.0" />
		<PackageReference Include="BarcodeScanner.Mobile.XamarinForms" Version="6.3.0.25" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.0" />
		<PackageReference Include="Grpc.Core" Version="2.46.6" />
		<PackageReference Include="Grpc.Core.Xamarin" Version="2.44.0" />
		<PackageReference Include="LiteDB" Version="5.0.16" />
		<PackageReference Include="MagicOnion.Client" Version="5.1.6" />
		<PackageReference Include="MarcTron.Admob" Version="1.9.0.3" />
		<PackageReference Include="MemoryPack" Version="1.9.13" />
		<PackageReference Include="Microsoft.AppCenter.Analytics" Version="5.0.1" />
		<PackageReference Include="Microsoft.AppCenter.Crashes" Version="5.0.1" />
		<PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="5.2.9" />
		<PackageReference Include="Plugin.MediaManager.Forms" Version="1.1.1" />
		<PackageReference Include="Polly" Version="7.2.3" />
		<PackageReference Include="Rg.Plugins.Popup" Version="2.1.0" />
		<PackageReference Include="Riok.Mapperly" Version="2.8.0" />
		<PackageReference Include="SkiaSharp.Views.Forms" Version="2.88.3" />
		<PackageReference Include="Xamarin.Auth" Version="1.7.0" />
		<PackageReference Include="Xamarin.CommunityToolkit" Version="2.0.6" />
		<PackageReference Include="Xamarin.FFImageLoading.Forms" Version="2.4.11.982" />
		<PackageReference Include="Xamarin.FFImageLoading.Svg.Forms" Version="2.4.11.982" />
		<PackageReference Include="Xamarin.FFImageLoading.Transformations" Version="2.4.11.982" />
		<PackageReference Include="Xamarin.Forms" Version="5.0.0.2599-pre1" />
		<PackageReference Include="Xamarin.Essentials" Version="1.8.0-preview1" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Picator.Realtime.Common\Picator.Realtime.Common.csproj" />
	  <ProjectReference Include="..\..\XamDrawingView\XamDrawingView.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Resources\Text\AppResource.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>AppResource.resx</DependentUpon>
	  </Compile>
	  <Compile Update="Views\ProfileSettingsPage.xaml.cs">
	    <DependentUpon>ProfileSettingsPage.xaml</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Update="Controls\BorderedEntry.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Controls\CircularProgressBar.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Controls\CopyButton.xaml">
	    <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Controls\ShareButton.xaml">
	    <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Resources\Text\AppResource.resx">
	    <Generator>ResXFileCodeGenerator</Generator>
	    <LastGenOutput>AppResource.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Views\BarcodeScannerView.xaml">
	    <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Views\ConfirmEmailPage.xaml">
	    <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Views\GamePage.xaml">
	    <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Views\LoginPage.xaml">
	    <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Views\Popups\WaitingView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Views\ProfileSettingsPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Views\StartNewGamePage.xaml">
	    <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Views\TimerGameView.xaml">
	    <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
	  </EmbeddedResource>
	</ItemGroup>
</Project>