<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>e5bf973a-c7ab-4f69-8a3b-9e378e630b94</UserSecretsId>
    <NoWarn>$(NoWarn);ASPIREJAVASCRIPT001</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Kubernetes" Version="13.4.6-preview.1.26319.6" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.4.6" />
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.4.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Picator.Api\Picator.Api.csproj" />
    <ProjectReference Include="..\Picator.ExternalAuth\Picator.ExternalAuth.csproj" />
    <ProjectReference Include="..\Picator.Invitement\Picator.Invitement\Picator.Invitement.csproj" />
    <ProjectReference Include="..\Picator.Realtime\Picator.Realtime.csproj" />
  </ItemGroup>

</Project>
