---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: picator-externalauth
  labels:
    app: picator-externalauth
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: picator-externalauth
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: picator-externalauth
    spec:
      containers:
      - name: picator-externalauth
        image: picator-externalauth:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: picator-externalauth-env
        - secretRef:
            name: picator-externalauth-secrets
      terminationGracePeriodSeconds: 180