<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Picator.Common.Data\Picator.Common.Data.csproj" />
    <ProjectReference Include="..\Picator.Data\Picator.Data.csproj" />
  </ItemGroup>
</Project>